### PR TITLE
12.0 afc 1938

### PR DESCRIPTION
**Pull request by SebastianGieser-Vertel**

### CODE REVIEW

**Comment by hans-olofsson-AF** [comment]
_213 log.log_message(AISF_OFFICER_SYNC_PROCESS, eventid, "SYNC STARTED", objectid=signature)_

As the message is for the relation signature -> office_code the objectid should be  signature and office-code combined, separated by a dash. Create a variable with the name object_id and set its value to signature + "-"  + office code as the relation is the actual object being handled.

AISF_OFFICER_SYNC_PROCESS = "AIS-F OFFICER SYNC" should be changed to:
AISF_OFFICER_OFFICE_SYNC_PROCESS = "AIS-F OFFICER-OFFICE SYNC" as it is the relation that is being synced.

**Comment by hans-olofsson-AF** [comment]
_Row 224 - 229_

When a res.users object has been created log it with info_1="officer create" and do not set status.

If the res.users-object could not be created  this should also be logged with an error-message given. In this case status should be set to false and no further processing of the message should be done

**Comment by hans-olofsson-AF** [comment]
_if msg_type == "delete":_

Handle the logging in the same way as for the creation of an officer, i.e. log both success and failure. Set the value for step (the 3rd argument) to OFFICER_OFFICE_SYNC (set the value for the constant to "OFFICER-OFFICE-SYNC". Set value for office_2 to be "officer-office delete"

**Comment by hans-olofsson-AF** [comment]
_elif msg_type == "create":_

Handle this in the same way as: _if msg_type == "delete":_

**Comment by hans-olofsson-AF** [comment]
As a message will not be removed from IPF AMQ until it is acke:ed or nack:ed we have implemented a function in af_process_log that keeps track of how many times a message is handled. If a defined threshold is passed an exception will be thrown, in this case the message should be acked/nacked as the logger will throw the same exception again when it is called and so on. See odoo-base/partner_mq_ipf/models/res_partner.py for an example of how it could be handled.

**Review by timforsstromAF — APPROVED** [review]
Remove commented code 
# class SampleListener(object): ...

**Comment by hans-olofsson-AF** [comment]
As multiple loggings will be done in a scenario where the officer is missing, the office is missing and the relation is created, the info-attributes should be used so we can keep track of what has happened. Use info_1 if the officer is created or changed, use info_2 if the office is changed or created and user info_3 for the handling of the relation officer-office.

When all steps in the process are finished, log that the process has been completed. For inspiration: take a look at odoo-base/partner_mq_ipf/models/res_partner.py and odoo-af/af_aisf_jobseeker_sync/models/res_partner.py

**Pull request merged**
