### PR TITLE
[ADD] partner_view_360, af_hide_top_todo_icons: AFC-1402 Removed func…

### PR DESCRIPTION
**Pull request by rupareliyahemangi145**
…tionality of hiding hide top icons from partner_view_360 and Added new module af_hide_top_todo_icons to add functionality for hiding icons.

### CODE REVIEW

**Comment by SebastianGieser-Vertel** [comment]
Hi
The init file is empty. 
Could you please correct this?

**Comment by rupareliyahemangi145** [comment]
Hi @SebastianGieser-Vertel 
What should be in init file? Licensing term? Because there no need to import anything in init file.

**Comment by SebastianGieser-Vertel** [comment]
I thought that maybe it could be deleted, however after a quick test I realized it's a must have for module installation and since there's no need to import anything it's good as is.

**Comment by rupareliyahemangi145** [comment]
Ok @SebastianGieser-Vertel

**Pull request merged**
